/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package triki;

import java.awt.Image;
import static java.lang.Thread.sleep;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sesca
 */
public class juego extends javax.swing.JFrame {

public ImageIcon imgx[];
public JLabel casilla[];
public int variables[],variables2[];
public int cont=0,av=0,bv=0,cv=0,dv=0,ev=0,fv=0,gv=0,hv=0,iv=0;
public int av1=0,bv1=0,cv1=0,dv1=0,ev1=0,fv1=0,gv1=0,hv1=0,iv1=0;
public String jugador="";
public String jug1="",jug2="";
public boolean val1=true,val2=true,val3=true,val4=true,val5=true;
public int radom,radom2;
public int imgt=0,contadorj1=0,contadorj2=0,contadorempate=0;

    public juego() throws InterruptedException {
        initComponents();
        triki();
        imgx = new ImageIcon[3];
        casilla = new JLabel[9];
        variables = new int[9];
        variables2 = new int[9];
        nombrej1.setText(""+jug1);
        nombrej2.setText(""+jug2);

        this.setLocationRelativeTo(null);
        Image icon=new ImageIcon(getClass().getResource("logoj.png")).getImage();
        setIconImage(icon);
        imgx[0] = new ImageIcon(getClass().getResource("/img/o.png"));
        imgx[1] = new ImageIcon(getClass().getResource("/img/x.png"));
        imgx[2] = new ImageIcon(getClass().getResource("/img/n.png"));
        casilla[0]=a;
        casilla[1]=b;
        casilla[2]=c;
        casilla[3]=d;
        casilla[4]=e;
        casilla[5]=f;
        casilla[6]=g;
        casilla[7]=h;
        casilla[8]=i;
        variables[0]=av;
        variables[1]=bv;
        variables[2]=cv;
        variables[3]=dv;
        variables[4]=ev;
        variables[5]=fv;
        variables[6]=gv;
        variables[7]=hv;
        variables[8]=iv;
        variables2[0]=av1;
        variables2[1]=bv1;
        variables2[2]=cv1;
        variables2[3]=dv1;
        variables2[4]=ev1;
        variables2[5]=fv1;
        variables2[6]=gv1;
        variables2[7]=hv1;
        variables2[8]=iv1;

        
        
        if(jug1=="Pc"){
        radom=random();

            
            System.out.println("Numero variable de la primera entrada "+radom);
            if(variables[radom-1]==0){  
      
            casilla[radom-1].setIcon(imgx[imgt]);
            variables[radom-1]=1;
            variables2[radom-1]=1;
            detener();
            }
        
        }else{imgt=1;}
        
        
       
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        c = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        b = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        a = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        e = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        d = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        f = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        g = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        h = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        i = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombrej1 = new javax.swing.JLabel();
        nombrej2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aMousePressed(evt);
            }
        });
        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(a, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(e, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(e, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(d, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(d, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(f, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(f, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        g.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(h, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(h, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(i, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(i, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/titulojuego.png"))); // NOI18N

        nombrej1.setFont(new java.awt.Font("Chiller", 0, 72)); // NOI18N
        nombrej1.setForeground(new java.awt.Color(255, 255, 255));

        nombrej2.setFont(new java.awt.Font("Chiller", 0, 72)); // NOI18N
        nombrej2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/java.png"))); // NOI18N

        j1.setBackground(new java.awt.Color(255, 255, 255));
        j1.setFont(new java.awt.Font("Chiller", 0, 72)); // NOI18N
        j1.setForeground(new java.awt.Color(255, 255, 255));
        j1.setText("0");

        j2.setBackground(new java.awt.Color(255, 255, 255));
        j2.setFont(new java.awt.Font("Chiller", 0, 72)); // NOI18N
        j2.setForeground(new java.awt.Color(255, 255, 255));
        j2.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombrej1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nombrej2)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(nombrej1)
                .addGap(9, 9, 9)
                .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombrej2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(60, 175, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(jug1=="pc"){
          JOptionPane.showMessageDialog(null,"Jugador "+jug1+" veces ganadas: "+contadorj1+"\n"+"Jugador "+jug2+" veces ganadas: "+contadorj2+"\n"+"Empates: "+contadorempate);
        }else{
          JOptionPane.showMessageDialog(null,"Jugador "+jug2+" veces ganadas: "+contadorj1+"\n"+"Jugador "+jug1+" veces ganadas: "+contadorj2+"\n"+"Empates: "+contadorempate);
        }



    

        if(JOptionPane.showConfirmDialog(rootPane,"¿Desea salir del juego?","Triki!",JOptionPane.YES_OPTION,JOptionPane.ERROR_MESSAGE)==JOptionPane.YES_OPTION){
            triki i = new triki();
            i.setVisible(true);
            this.setVisible(false);
        }
        else{
            setDefaultCloseOperation(0);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyPressed
           // TODO add your handling code here:
    }//GEN-LAST:event_aKeyPressed

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
          // cuando se da click en "a"
        variables[0]=1;
        
        a.setIcon(imgx[imgt]);
        if(imgt==0){
        variables2[0]=1;
        }else{
        variables2[0]=4;}
        detener(); 
        try{tiempo();}catch(Exception e){};
        while(val4){
        radom2=random();
            System.out.println("Numero variable de clic "+radom2);
            if(variables[radom2-1]==0){        
            casilla[radom2-1].setIcon(imgx[imgt]);
            variables[radom2-1]=1;
            variables2[radom2-1]=1;
            val4=false;
            detener();
            }
        }
        val4=true;
        
        limpiar();
    }//GEN-LAST:event_aMouseClicked

    private void aMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMousePressed
        a.setIcon(imgx[1]);  // TODO add your handling code here:
    }//GEN-LAST:event_aMousePressed

    private void bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseClicked
        variables[1]=1;
        
        b.setIcon(imgx[imgt]);
        if(imgt==0){
        variables2[1]=1;
        }else{
        variables2[1]=4;}
        detener(); 
        try{tiempo();}catch(Exception e){}; 
        while(val4){
        radom2=random();
            System.out.println("Numero variable de clic "+radom2);
            if(variables[radom2-1]==0){        
            casilla[radom2-1].setIcon(imgx[imgt]);
            variables[radom2-1]=1;
            variables2[radom2-1]=1;
            val4=false;
            detener();
            }
        }
        val4=true;

        limpiar();

    }//GEN-LAST:event_bMouseClicked

    private void cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseClicked
        variables[2]=1;
            
        c.setIcon(imgx[imgt]);
        if(imgt==0){
        variables2[2]=1;
        }else{
        variables2[2]=4;}
        detener(); 
        try{tiempo();}catch(Exception e){}; 
        while(val4){
        radom2=random();
            System.out.println("Numero variable de clic "+radom2);
            if(variables[radom2-1]==0){        
            casilla[radom2-1].setIcon(imgx[imgt]);
            variables[radom2-1]=1;
            variables2[radom2-1]=1;
            val4=false;
            detener();
            }
        }
        val4=true;
   
        limpiar();// TODO add your handling code here:
    }//GEN-LAST:event_cMouseClicked

    private void dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseClicked
        variables[3]=1;
         
        d.setIcon(imgx[imgt]);  
        if(imgt==0){
        variables2[3]=1;
        }else{
        variables2[3]=4;}
        detener();
        try{tiempo();}catch(Exception e){}; 
        while(val4){
        radom2=random();
            System.out.println("Numero variable de clic "+radom2);
            if(variables[radom2-1]==0){        
            casilla[radom2-1].setIcon(imgx[imgt]);
            variables[radom2-1]=1;
            variables2[radom2-1]=1;
            val4=false;
            detener();
            }
        }
        val4=true;

   
        limpiar();   // TODO add your handling code here:
    }//GEN-LAST:event_dMouseClicked

    private void eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eMouseClicked
        variables[4]=1;
        e.setIcon(imgx[imgt]); 
        if(imgt==0){
          variables2[4]=1;
        }else{
        variables2[4]=4;}
        detener(); 
        try{tiempo();}catch(Exception e){}; 
        while(val4){
        radom2=random();
            System.out.println("Numero variable de clic "+radom2);
            if(variables[radom2-1]==0){        
            casilla[radom2-1].setIcon(imgx[imgt]);
            variables[radom2-1]=1;
            variables2[radom2-1]=1;
            val4=false;
            detener();
            }
        }
        val4=true;

        limpiar();   // TODO add your handling code here:
    }//GEN-LAST:event_eMouseClicked

    private void fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fMouseClicked
        variables[5]=1;
        f.setIcon(imgx[imgt]); 
        if(imgt==0){
        variables2[5]=1;
        }else{
        variables2[5]=4;} 
        detener(); 
        try{tiempo();}catch(Exception e){}; 
        while(val4){
        radom2=random();
            System.out.println("Numero variable de clic "+radom2);
            if(variables[radom2-1]==0){        
            casilla[radom2-1].setIcon(imgx[imgt]);
            variables[radom2-1]=1;
            variables2[radom2-1]=1;
            val4=false;
            detener();
            }
        }
        val4=true;

        limpiar();   // TODO add your handling code here:
    }//GEN-LAST:event_fMouseClicked

    private void gMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMouseClicked
        variables[6]=1;   
        g.setIcon(imgx[imgt]); 
        if(imgt==0){
        variables2[6]=1;
        }else{
        variables2[6]=4;}
        detener();  
        while(val4){
        radom2=random();
            System.out.println("Numero variable de clic "+radom2);
            if(variables[radom2-1]==0){        
            casilla[radom2-1].setIcon(imgx[imgt]);
            variables[radom2-1]=1;
            variables2[radom2-1]=1;
            val4=false;
            detener();
            }
        }
        val4=true;
 
        limpiar();     // TODO add your handling code here:
    }//GEN-LAST:event_gMouseClicked

    private void hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hMouseClicked
        variables[7]=1;
         
        h.setIcon(imgx[imgt]); 
        if(imgt==0){
        variables2[7]=1;
        }else{
        variables2[7]=4;}
        detener(); 
        try{tiempo();}catch(Exception e){}; 
        while(val4){
        radom2=random();
            System.out.println("Numero variable de clic "+radom2);
            if(variables[radom2-1]==0){        
            casilla[radom2-1].setIcon(imgx[imgt]);
            variables[radom2-1]=1;
            variables2[radom2-1]=1;
            val4=false;
            detener();
            }
        }
        val4=true;

        limpiar();     // TODO add your handling code here:
    }//GEN-LAST:event_hMouseClicked

    private void iMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseClicked
        variables[8]=1;
        i.setIcon(imgx[imgt]);
        if(imgt==0){
        variables2[8]=1;
        }else{
        variables2[8]=4;}
        detener();
        try{tiempo();}catch(Exception e){}; 
        while(val4){
        radom2=random();
            System.out.println("Numero variable de clic "+radom2);
            if(variables[radom2-1]==0){        
            casilla[radom2-1].setIcon(imgx[imgt]);
            variables[radom2-1]=1;
            variables2[radom2-1]=1;
            val4=false;
            detener();
            }
        }
        val4=true;

        limpiar();   
  // TODO add your handling code here:
    }//GEN-LAST:event_iMouseClicked


public void triki(){

while(val1){
jug1=JOptionPane.showInputDialog("Escribe el nombre del jugador 1");
if(jug1==""){
    val1=false;
}else{
    val1=false;};
}

if(jugador ==""){
jugador =(JOptionPane.showInputDialog(null,"Selecciona la persona que será jugador 1, TRIKI","Jugador inicial",JOptionPane.PLAIN_MESSAGE,null,new Object[]{jug1,"PC"},"Selecciona")).toString();

}
String jug3="";
if(jugador==jug1){
jug1=jugador;
jug2="Pc";
}else{
jug3=jug1;
jug1="Pc";
jug2=jug3;
}
}





   public void limpiar(){
        int sum1=0,sum2=0,sum3=0,sum4=0,sum5=0,sum6=0,sum7=0,sum8=0,vals=0;
        sum1=variables2[0]+variables2[1]+variables2[2];
        sum2=variables2[3]+variables2[4]+variables2[5];
        sum3=variables2[6]+variables2[7]+variables2[8];

        sum4=variables2[0]+variables2[3]+variables2[6];
        sum5=variables2[1]+variables2[4]+variables2[7];
        sum6=variables2[2]+variables2[5]+variables2[8];

        sum7=variables2[0]+variables2[4]+variables2[8];
        sum8=variables2[2]+variables2[4]+variables2[6];

        System.out.println(sum8+" "+sum4+" "+sum5+" "+sum6+" "+sum7+" "+sum1+" "+sum2+" "+sum3);

        //suma 3 es gana 0, suma 12 gana x, suma total 57
       
        
        if(sum1==3||sum2==3||sum3==3||sum4==3||sum5==3||sum6==3||sum7==3||sum8==3){
        for(int i=0;i<9;i++){
        variables[i]=1;
        }
        vals=1;
        imgt=0;

       if(jug1=="pc"){
             contadorj1=contadorj1+1;
             j1.setText(""+contadorj1);
            JOptionPane.showMessageDialog(rootPane,"Gana Jugador: "+jug2);
        }else{
            contadorj2=contadorj2+1;
             j1.setText(""+contadorj2);
            JOptionPane.showMessageDialog(rootPane,"Gana Jugador: "+jug1);
        }
       
        for(int k=0;k<9;k++){
        casilla[k].setIcon(imgx[2]);
        variables[k]=1;
        variables2[k]=1;
        }
        sum1=0;sum2=0;sum3=0;sum4=0;sum5=0;sum6=0;sum7=0;sum8=0;
        System.out.println("Prueba de gana 3 = "+sum8+" "+sum4+" "+sum5+" "+sum6+" "+sum7+" "+sum1+" "+sum2+" "+sum3);
        
        if(jug1!="Pc"){
        detener();}
        }

        if(sum1==12||sum2==12||sum3==12||sum4==12||sum5==12||sum6==12||sum7==12||sum8==12){
        
        for(int i=0;i<9;i++){
        variables[i]=1;
        }
        vals=1;
        imgt=0;   
        if(jug1=="pc"){
             contadorj1=contadorj1+1;
             j1.setText(""+contadorj1);
            JOptionPane.showMessageDialog(rootPane,"Gana Jugador: "+jug2);
        }else{
            contadorj2=contadorj2+1;
             j1.setText(""+contadorj2);
            JOptionPane.showMessageDialog(rootPane,"Gana Jugador: "+jug1);
        }
        sum1=0;sum2=0;sum3=0;sum4=0;sum5=0;sum6=0;sum7=0;sum8=0;
        for(int k=0;k<9;k++){
        casilla[k].setIcon(imgx[2]);
        variables[k]=1;
        variables2[k]=1;
        }if(jug1!="Pc"){
        detener();}

        System.out.println("Prueba de gana 12 = "+sum8+" "+sum4+" "+sum5+" "+sum6+" "+sum7+" "+sum1+" "+sum2+" "+sum3);
        }


        cont=variables[0]+variables[1]+variables[2]+variables[3]+variables[4]+variables[5]+variables[6]+variables[7]+variables[8]+vals;
        System.out.println("prueba antes del =al 10 y al =9 --->"+cont);

              
        if(cont==10){
        for(int i=0;i<9;i++){
        casilla[i].setIcon(imgx[2]);
        variables[i]=0;
        variables2[i]=0;
        }
        sum1=0;sum2=0;sum3=0;sum4=0;sum5=0;sum6=0;sum7=0;sum8=0;vals=0;
        imgt=0;
        val5=true;
        while(val5){
        if(jug1=="Pc"){
        radom=random();
            System.out.println("Numero variable de la segunda jugada "+radom);
            if(variables[radom-1]==0){        
            casilla[radom-1].setIcon(imgx[imgt]);
            variables[radom-1]=1;
            variables2[radom-1]=1;
            val5=false;
            detener();
            }
       
        } val5=false;
        } cont=0; if(jug1!="Pc"){
        detener();}
        }

        System.out.println("Prueba contadot antes del 9 número ->"+cont);
        if(cont==9){
        JOptionPane.showMessageDialog(rootPane,jug1+" y "+jug2+" Empate, nadie gana");

        for(int k=0;k<9;k++){
        casilla[k].setIcon(imgx[2]);
        variables[k]=0;
        variables2[k]=0;
        }

        sum1=0;sum2=0;sum3=0;sum4=0;sum5=0;sum6=0;sum7=0;sum8=0;vals=0;
        imgt=0;
        contadorempate=contadorempate+1; 
        val5=true;
        while(val5){
        if(jug1=="Pc"){
        radom=random();
            System.out.println("Numero variable de la primera entrada "+radom);
            if(variables[radom-1]==0){        
            casilla[radom-1].setIcon(imgx[imgt]);
            variables[radom-1]=1;
            variables2[radom-1]=1;
            val5=false;
            detener();
            }
        } val5=false;
        
        }

        if(jug1!="Pc"){
        detener();}
        }  

        }

public void detener(){
if(imgt == 0){
imgt=1;
}
else{
imgt=0;}

}


public int random(){

    int min = 1;
    int max = 8;
    Random random = new Random();
    int value = random.nextInt(max + min) + min;
    System.out.println(value);

return value;
}

public void tiempo() throws InterruptedException{

Thread.sleep(1200);
}


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               try{new juego().setVisible(true);}catch(Exception e){}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e;
    private javax.swing.JLabel f;
    private javax.swing.JLabel g;
    private javax.swing.JLabel h;
    private javax.swing.JLabel i;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nombrej1;
    private javax.swing.JLabel nombrej2;
    // End of variables declaration//GEN-END:variables
}
